### ISSUE TITLE
Emotes don't wrap in chat

### ISSUE THREAD

**Issue by LittleBigBug** [XspeedPL/Streamotes#10]
Emotes in chat messages will go off screen if at the end of messages or if there's just a lot of them
![image](https://github.com/XspeedPL/Streamotes/assets/10341753/80edc371-99d6-43fe-a54e-369a0f5c9d08)

**Comment by XspeedPL** [comment]
I cannot reproduce the issue in 1.2.2, assume it was fixed among other issues
