### ISSUE TITLE
BTTV channel emotes seem to load inconsistently

### ISSUE THREAD

**Issue by LittleBigBug** [XspeedPL/Streamotes#12]
Several emotes from BTTV that should be there (could be a problem with other emote providers that I haven't noticed yet) aren't loading or rendering consistently

![image](https://github.com/XspeedPL/Streamotes/assets/10341753/5a2b3608-70b7-407e-b7bf-64fb7077a074)

gachiW is added to the channel. Seems like a coinflip whether one emote loads or not.

**Comment by XspeedPL** [comment]
No response for 6 months, closing as stale
