### ISSUE TITLE
Is there a way to remove the message when you log in?

### ISSUE THREAD

**Issue by eydrien-dev** [XspeedPL/Streamotes#15]
I don't want for the game to show the message of emotes getting loaded in everytime I open the game, but couldn't find anything on the files that were readable.

**Comment by XspeedPL** [comment]
The problem is that people with slower connections might experience delays with emote loading

If not by chat some kind of temporary notification should be put in place to tell the user that emotes are available

**Comment by XspeedPL** [comment]
@MJRamon please file a new issue if it's unrelated to the current one
