### ISSUE TITLE
Duplicated emote

### ISSUE THREAD

**Issue by M1B4ND** [XspeedPL/Streamotes#22]
Some emotes appear to be displayed twice, like the peepoCowboy in the image. Is the problem mine or not?

![image](https://github.com/XspeedPL/Streamotes/assets/70129787/74b7bd89-e913-42a5-9c1f-994e3d5f1bcb)

**Comment by XspeedPL** [comment]
Thanks for the report, it's indeed a bug. All emotes are drawn twice, I didn't notice it before

**Comment by XspeedPL** [comment]
Do you still see the problem in new versions?

**Comment by M1B4ND** [comment]
![image](https://github.com/user-attachments/assets/0ea14612-0e31-4944-ab2b-2e36943fe304)

Version 1.2.2

it seems to be only peepo
