### ISSUE TITLE
Can't see channel BTTV/7tv emotes

### ISSUE THREAD

**Issue by DoctorBub** [XspeedPL/Streamotes#23]
tried reinstalling the mod multiple times. its set up on a server im running and one of the members of the server who isnt me can see the emotes just fine, but i cant see them. i can see FFZ channel emotes and all global emotes, but no BTTV/7tv emotes from any channel. the issue seems to be client side. any ideas regarding cause/fix? i know i havent given much info to work with, but thats all the info i have. the settings to show these emotes are set to true in the config and in the mod menu mod. if BTTV and 7tv emotes loaded, there would be well over 1000 loaded.
![streamotetroubleshooting](https://github.com/XspeedPL/Streamotes/assets/174417491/998bb419-88ca-441f-8970-cbfed0ea70bf)
![streamotetroubleshooting2](https://github.com/XspeedPL/Streamotes/assets/174417491/1dbd0493-c074-4dd9-becb-ca6dcaf7516c)

**Comment by DoctorBub** [comment]
`[03:14:01] [Render thread/INFO]: [System] [CHAT] Streamotes: Received emote config, starting loading [03:14:01] [7TV Emote Loader/ERROR]: Failed to load 7TV subscriber emotes xeed.mc.streamotes.api.EmoteLoaderException: Unhandled exception 	at xeed.mc.streamotes.addon.pack.X7tvChannelPack.loadMetadata(X7tvChannelPack.java:52) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$5(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.tryFewTimes(Streamotes.java:111) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$6(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$startLoadingDaemon$3(Streamotes.java:86) ~[streamotes-1.0.0+1.21.jar:?] 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://twitchtracker.com/Yabbe 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998) ~[?:?] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?] 	at java.base/java.net.URL.openStream(URL.java:1325) ~[?:?] 	at xeed.mc.streamotes.addon.TwitchEmotesAPI.getChannelId(TwitchEmotesAPI.java:50) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.addon.pack.X7tvChannelPack.loadMetadata(X7tvChannelPack.java:23) ~[streamotes-1.0.0+1.21.jar:?] 	... 5 more [03:14:01] [BTTV Emote Loader/ERROR]: Failed to load BTTV subscriber emotes xeed.mc.streamotes.api.EmoteLoaderException: Unhandled exception 	at xeed.mc.streamotes.addon.pack.BTTVChannelPack.loadMetadata(BTTVChannelPack.java:47) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$5(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.tryFewTimes(Streamotes.java:111) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$6(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$startLoadingDaemon$3(Streamotes.java:86) ~[streamotes-1.0.0+1.21.jar:?] 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://twitchtracker.com/Yabbe 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998) ~[?:?] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?] 	at java.base/java.net.URL.openStream(URL.java:1325) ~[?:?] 	at xeed.mc.streamotes.addon.TwitchEmotesAPI.getChannelId(TwitchEmotesAPI.java:50) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.addon.pack.BTTVChannelPack.loadMetadata(BTTVChannelPack.java:25) ~[streamotes-1.0.0+1.21.jar:?] 	... 5 more [03:14:01] [Render thread/INFO]: Starting JEI... [03:14:01] [Render thread/INFO]: Registering item subtypes... [03:14:01] [Render thread/INFO]: Registering item subtypes took 4.477 ms [03:14:01] [Render thread/INFO]: Registering fluid subtypes... [03:14:01] [Render thread/INFO]: Registering fluid subtypes took 2.524 ms [03:14:01] [Render thread/INFO]: Registering ingredients... [03:14:01] [Twitch Emote Loader/ERROR]: Failed to load Twitch subscriber emotes xeed.mc.streamotes.api.EmoteLoaderException: Unhandled exception 	at xeed.mc.streamotes.addon.pack.TwitchSubscriberPack.loadMetadata(TwitchSubscriberPack.java:59) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$5(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.tryFewTimes(Streamotes.java:111) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$6(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$startLoadingDaemon$3(Streamotes.java:86) ~[streamotes-1.0.0+1.21.jar:?] 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://twitchtracker.com/Yabbe 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998) ~[?:?] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?] 	at java.base/java.net.URL.openStream(URL.java:1325) ~[?:?] 	at xeed.mc.streamotes.addon.TwitchEmotesAPI.getChannelId(TwitchEmotesAPI.java:50) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.addon.pack.TwitchSubscriberPack.loadMetadata(TwitchSubscriberPack.java:21) ~[streamotes-1.0.0+1.21.jar:?] 	... 5 more [03:14:01] [Render thread/INFO]: Registering ingredients: jei:minecraft took 116.5 milliseconds [03:14:01] [Render thread/INFO]: Registering ingredients took 117.1 ms [03:14:01] [Render thread/INFO]: Registering Mod Info... [03:14:01] [Render thread/INFO]: Registering Mod Info took 290.6 Î¼s [03:14:01] [Render thread/INFO]: Registering categories... [03:14:01] [Render thread/INFO]: Registering categories: jei:minecraft took 29.71 milliseconds [03:14:01] [Render thread/INFO]: Registering categories took 32.11 ms [03:14:01] [Render thread/INFO]: Registering vanilla category extensions... [03:14:01] [Render thread/INFO]: Registering vanilla category extensions took 1.821 ms [03:14:01] [Render thread/INFO]: Registering recipe catalysts... [03:14:01] [Render thread/INFO]: Registering recipe catalysts took 671.2 Î¼s [03:14:01] [Render thread/INFO]: Registering advanced plugins... [03:14:01] [Render thread/INFO]: Registering advanced plugins took 498.0 Î¼s [03:14:01] [Render thread/INFO]: Building recipe registry... [03:14:01] [Render thread/INFO]: Building recipe registry took 11.30 ms [03:14:01] [Render thread/INFO]: Registering recipes... [03:14:01] [BTTV Emote Loader/ERROR]: Failed to load BTTV subscriber emotes xeed.mc.streamotes.api.EmoteLoaderException: Unhandled exception 	at xeed.mc.streamotes.addon.pack.BTTVChannelPack.loadMetadata(BTTVChannelPack.java:47) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$5(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.tryFewTimes(Streamotes.java:111) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$6(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$startLoadingDaemon$3(Streamotes.java:86) ~[streamotes-1.0.0+1.21.jar:?] 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://twitchtracker.com/Yabbe 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998) ~[?:?] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?] 	at java.base/java.net.URL.openStream(URL.java:1325) ~[?:?] 	at xeed.mc.streamotes.addon.TwitchEmotesAPI.getChannelId(TwitchEmotesAPI.java:50) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.addon.pack.BTTVChannelPack.loadMetadata(BTTVChannelPack.java:25) ~[streamotes-1.0.0+1.21.jar:?] 	... 5 more [03:14:01] [7TV Emote Loader/ERROR]: Failed to load 7TV subscriber emotes xeed.mc.streamotes.api.EmoteLoaderException: Unhandled exception 	at xeed.mc.streamotes.addon.pack.X7tvChannelPack.loadMetadata(X7tvChannelPack.java:52) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$5(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.tryFewTimes(Streamotes.java:111) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$6(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$startLoadingDaemon$3(Streamotes.java:86) ~[streamotes-1.0.0+1.21.jar:?] 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://twitchtracker.com/Yabbe 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998) ~[?:?] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?] 	at java.base/java.net.URL.openStream(URL.java:1325) ~[?:?] 	at xeed.mc.streamotes.addon.TwitchEmotesAPI.getChannelId(TwitchEmotesAPI.java:50) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.addon.pack.X7tvChannelPack.loadMetadata(X7tvChannelPack.java:23) ~[streamotes-1.0.0+1.21.jar:?] 	... 5 more [03:14:01] [Twitch Emote Loader/ERROR]: Failed to load Twitch subscriber emotes xeed.mc.streamotes.api.EmoteLoaderException: Unhandled exception 	at xeed.mc.streamotes.addon.pack.TwitchSubscriberPack.loadMetadata(TwitchSubscriberPack.java:59) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$5(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.tryFewTimes(Streamotes.java:111) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$processPacks$6(Streamotes.java:176) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.Streamotes.lambda$startLoadingDaemon$3(Streamotes.java:86) ~[streamotes-1.0.0+1.21.jar:?] 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?] Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://twitchtracker.com/Yabbe 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1998) ~[?:?] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599) ~[?:?] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223) ~[?:?] 	at java.base/java.net.URL.openStream(URL.java:1325) ~[?:?] 	at xeed.mc.streamotes.addon.TwitchEmotesAPI.getChannelId(TwitchEmotesAPI.java:50) ~[streamotes-1.0.0+1.21.jar:?] 	at xeed.mc.streamotes.addon.pack.TwitchSubscriberPack.loadMetadata(TwitchSubscriberPack.java:21) ~[streamotes-1.0.0+1.21.jar:?] 	... 5 more [03:14:01] [Twitch Emote Loader/INFO]: Loaded emote metadata: 4Head, 7TV, ANELE, AYAYA, AlienDance, AngelThump, ApuApustaja, ArgieB8, ArsonNoSexy, AsexualPride, AsianGlow, BCWarrior, BOP, BORT, BabyRage, BaileyChamp, BangbooBounce, BasedGod, BatChest, BeanieHipster, BegWan, BibleThump, BigBrother, BigPhish, BillyApprove, BisexualPride, BlackLivesMatter, BlargNaut, BloodTrail, BrainSlug, BroBalt, BrokeBack, BuddhaBar, CaitlynS, CandianRage, CarlSmile, CatBag, ChefFrank, ChewyYAY, CiGrip, Clap, Clap2, ConcernDoge, CoolCat, CoolStoryBob, CorgiDerp, CrayonTime, CrreamAwk, CruW, CurseLit, DAESuppy, DBstyle, DansGame, DarkKnight, DarkMode, DatSauce, DatSheffy, DendiFace, DinoDance, DogChamp, DogFace, DoritosChip, DuckerZ, DxCat, EZ, EarthDay, EleGiggle, EntropyWins, ExtraLife, FBBlock, FBCatch, FBChallenge, FBPass, FBPenalty, FBRun, FBSpiral, FBtouchdown, FUNgineer, FailFish, FallCry, FallHalp, FallWinning, FamilyMan, FeelsAmazingMan, FeelsBadMan, FeelsBirthdayMan, FeelsDankMan, FeelsGoodMan, FeelsOkayMan, FeelsPumpkinMan, FeelsSnowMan, FeelsSnowyMan, FeelsStrongMan, FeelsWeirdMan, FireSpeed, FishMoley, FlawlessVictory, FootBall, FootGoal, FootYellow, ForSigmar, ForeverAlone, FrankerZ, FreakinStinkin, FutureMan, GabeN, GayPride, Gayge, GenderFluidPride, Getcamped, GingerPower, GivePLZ, GlitchCat, GlitchLit, GlitchNRG, GoatEmotey, GoldPLZ, GrammarKing, GuitarTime, GunRun, HSCheers, HSWP, HailHelix, HarleyWink, HassaanChop, HeyGuys, Hhhehehe, HolidayCookie, HolidayLog, HolidayPresent, HolidaySanta, HolidayTree, HotPokket, HungryPaimon, ImTyping, IntersexPride, InuyoFace, ItsBoshyTime, JKanStyle, Jebaited, Jebasted, JonCarnage, JulyFirst, KAPOW, KEKHeim, KKona, KaRappa, Kappa, KappaClaus, KappaCool, KappaPride, KappaRoss, KappaWealth, Kappu, Keepo, KevinTurtle, KingWorldCup, Kippa, KomodoHype, KonCha, Kreygasm, LUL, LaterSooner, LaundryBasket, Lechonk, LesbianPride, LilZ, LionOfYara, LuL, MVGame, ManChicken, Mau5, MaxLOL, MayaO, MechaRobot, MercyWing1, MercyWing2, MikeHogu, MingLee, ModLove, MorphinTime, MrDestructoid, MyAvatar, NaM, NewRecord, NiceTry, NinjaGrumpy, NomNom, NonbinaryPride, NotATK, NotLikeThis, OSFrog, O_O, O_o, OhMyDog, OneHand, OpieOP, OptimizePrime, PETPET, PJSalt, PJSugar, PMSTwin, PRChase, PanicVis, PansexualPride, PartyHat, PartyParrot, PartyTime, PeoplesChamp, PepePls, PermaSmug, PianoTime, PicoMause, PikaRamen, PinkMercy, PipeHype, PixelBob, PizzaTime, PogBones, PogChamp, PoleDoge, Poooound, PopCorn, PopGhost, PopNemo, PoroSad, PotFriend, PowerUpL, PowerUpR, PraiseIt, PrimeMe, PunOko, PunchTrees, RaccAttack, RainTime, RalpherZ, RareParrot, RarePepe, RebeccaBlack, RedCoat, ResidentSleeper, RitzMitz, RlyTho, RonSmug, RoxyPotato, RuleFive, RyuChamp, SMOrc, SSSsss, SUBprise, SabaPing, SaltyCorn, SeemsGood, SeriousSloth, ShadyLulu, ShazBotstix, ShoopDaWhoop, Shush, SillyChamp, SingsMic, SingsNote, SmoocherZ, SoBayed, SoonerLater, SourPls, SpiritEel, SqShy, Squid1, Squid2, Squid3, Squid4, Stare, SteerR, StinkyCheese, StinkyGlitch, StoneLightning, StrawBeary, SuperVinlin, SwiftRage, TBAngel, TF2John, TPFufun, TPcrunchyroll, TTours, TakeNRG, TaxiBro, TeaTime, TearGlove, TehePelo, ThankEgg, TheIlluminati, TheRinger, TheTarFu, TheThing, ThunBeast, TinyFace, TombRaid, TooSpicy, TransgenderPride, TriHard, TwaT, TwitchConHYPE, TwitchLit, TwitchRPG, TwitchSings, TwitchUnity, TwitchVotes, UWot, UnSane, UncleNox, VapeNation, VirtualHug, VisLaud, VoHiYo, VoteNay, VoteYea, WAYTOODANK, WTRuck, WatChuSay, WholeWheat, WhySoSerious, WineTime, Wowee, WubTF, WutFace, YooHoo, YouDontSay, YouWHY, ZliL, ZrehplaR, ZreknarF, ariW, bUrself, bleedPurple, bttvNice, cmonBruh, copyThis, cvHazmat, cvL, cvMask, cvR, duDudu, ffzCursed, ffzW, ffzX, ffzY, forsenGa, forsenPls, gachiBASS, gachiGASM, haHAA, imGlitch, mcaT, monkaS, notsquishY, nymnCorn, o_O, o_o, panicBasket, pastaThat, peepoHappy, peepoPls, peepoSad, peepoSquad, ppL, reckH, riPepperonis, sosGame, tehPoleCat, twitchRaid, yabbePog [03:14:01] [Twitch Emote Loader/INFO]: [System] [CHAT] Streamotes: Finished loading, 371 emotes`

**Comment by XspeedPL** [comment]
Hmmm, can you check if this website works for you:
 https://twitchtracker.com/Yabbe

**Comment by DoctorBub** [comment]
yeah that website works for me

**Comment by XspeedPL** [comment]
The mod uses that website to get Twitch channel information, and it looks like it is (was?) blocking you specifically for some reason

No clue why, but I guess supporting backup sources in case this happens to people would be a good idea

For now all you can do it wait a bit, the block should go away on its own eventually, but I can't get more specific than that I'm afraid

**Comment by DoctorBub** [comment]
oh... they could have target blocked me. i think i once had to solve a captcha to continue using it because i was opening hundreds of old clips

**Comment by DoctorBub** [comment]
can you think of any way around it like changing my IP or something?

**Comment by XspeedPL** [comment]
Changing your IP should do the trick if you can do it

I will try adding backup data providers but that's for next release

**Comment by XspeedPL** [comment]
Resolved by 42de38a, wait for 1.1.0 release
