### ISSUE TITLE
Backport new mod version to 1.19.x

### ISSUE THREAD

**Issue by ghost** [XspeedPL/Streamotes#25]
could you make this mod available for 1.19.3 or just 1.19 in general? I sadly don't know how to do stuff like this, wish I could do this, huge respect. Have a nice day

**Comment by XspeedPL** [comment]
Hi, thanks for showing interest in the mod :) 

Porting back is not trivial, due to changes under the hood in the game. Let's say if we can get at least 5 people wanting it (reacting or commenting) I'll do it.

**Comment by c0ozyy** [comment]
would be fun to have ngl :)

**Comment by Josuburga** [comment]
I would be interested in the backport for the 1.20.1, but I suppose that means more work to do 😅

**Comment by XspeedPL** [comment]
Putting in one-time effort is not that big of a deal, but with backporting you need to update all versions every time you want to change something. That's why it is so annoying to do.

**Comment by XspeedPL** [comment]
I see that the comment has hit 5 reacts, given that I already made a compatibility layer for different Minecraft versions, I'll look into backporting it to 1.19.4 as well.

@Josuburga 1.20.1 compatible version was released today, check it out :)
