### ISSUE TITLE
Streamotes unable to load 7tv emotes.

### ISSUE THREAD

**Issue by RadiantSoul** [XspeedPL/Streamotes#26]
7tv emotes no longer load.
tried to figure it out myself but couldnt find the problem
here are some error logs:
https://mclo.gs/5EfNqSI

if you are trying to get USER Id from a twitch username using twitchtracker. consider using this method instead https://discuss.dev.twitch.com/t/getting-user-ids/13806

**Comment by XspeedPL** [comment]
This is the same issue as #23 

Resolved by 42de38a
