### ISSUE TITLE
Shadows on text not displayed

### ISSUE THREAD

**Issue by RockeyWereWolfCodeAcademy** [XspeedPL/Streamotes#31]
Hello there! I am not really sure what to post here for your assistance, but when I compile this mod from sources outputed jar file causes all text in menus be without "shadows"
I compile just with ./gradlew build
With jar:
![изображение](https://github.com/user-attachments/assets/65093e77-7e25-4222-96b5-518f08da8a8b)
Without:
![изображение](https://github.com/user-attachments/assets/439456bf-c25d-4763-8bad-969a3835487e)

**Comment by XspeedPL** [comment]
Based on the logs you sent it is kind of hard to tell what could be the issue

**Comment by RockeyWereWolf** [comment]
> Based on the logs you sent it is kind of hard to tell what could be the issue

Which log would be helpfull?

here is latest.log from game's log folder https://pastebin.com/DuUfrbkA

**Comment by XspeedPL** [comment]
Looks like you have a bunch of other mods installed, try with just STREAMOTES and YACL installed

**Comment by RockeyWereWolf** [comment]
> Looks like you have a bunch of other mods installed, try with just STREAMOTES and YACL installed

just with fabric api, streamotes and yacl https://pastebin.com/xLbGQtyM
