### ISSUE TITLE
Shared Bttv emote vs Channel bttv emote

### ISSUE THREAD

**Issue by Hinzy-Admin** [XspeedPL/Streamotes#32]
Emotes that are "Shared BTTV emotes" don't show up ingame, while Emotes that are "Channel BTTV emotes" do, could it be made so that shared emotes could be toggled on?

**Comment by Hinzy-Admin** [comment]
![image](https://github.com/user-attachments/assets/8a326982-8a82-44cf-8dee-85abf34a46f5)
i think it should be pretty simple

**Comment by XspeedPL** [comment]
Both global and channel BTTV emotes seem to work fine, or are you talking about something else?

**Comment by Hinzy-Admin** [comment]
![Screenshot 2024-09-26 070923](https://github.com/user-attachments/assets/ee51c815-1965-41ee-ba98-ee9a3f08ec34)
![Screenshot 2024-09-26 070947](https://github.com/user-attachments/assets/0a48b430-2467-4e32-9ce6-0ac7fb10fff9)
I could be wrong with this, but there seems to be a 3rd type of emote "Shared Emote" 
![image](https://github.com/user-attachments/assets/af1e445e-dbe9-4523-84e9-abd312259a0f)
It referenced in the bttv api, i could be wrong tho

**Comment by XspeedPL** [comment]
Resolved in 7abafa7
