### ISSUE TITLE
[Aternos] Unable to add plugin to the server

### ISSUE THREAD

**Issue by KoCitrusMaker** [XspeedPL/Streamotes#34]
Due to the mod/plugin being categorized as a client-side mod, it is not possible to add the plugin in an Aternos server. Please add the plugin category in the Modrinth page. Thanks in advanced!

![image](https://github.com/user-attachments/assets/4b27487c-4d87-47a1-bcda-715d134bd0c2)

**Comment by XspeedPL** [comment]
I'm afraid there is no option to change what is displayed on the website, though the project panel tells me it is a plugin:
![image](https://github.com/user-attachments/assets/f6dedd16-6bb3-452b-a951-afa814b2749d)

Both of the following links work correctly (one to the mod, and another to the plugin):
https://modrinth.com/mod/streamotes/version/1.2.3+1.21
https://modrinth.com/plugin/streamotes/version/1.2.3

Not sure what else could be done.

**Comment by XspeedPL** [comment]
Looks like this might be related: https://github.com/modrinth/code/issues/2153

**Comment by KoCitrusMaker** [comment]
It seems like the only option would be making separate pages for the client-side mod and the plugin separately, but I'm aware that would be inconvenient/too much trouble. Thanks anyways for the info!

**Comment by XspeedPL** [comment]
Got additional info directly from Modrinth support
![image](https://github.com/user-attachments/assets/a92df259-aa56-4da3-bf27-4c6ef9f7a7a1)
