### ISSUE TITLE
Prefix to emotes

### ISSUE THREAD

**Issue by Hinzy-Admin** [XspeedPL/Streamotes#37]
give an option to add a prefix to emotes, for example, instead of typing peepoHappy you would have to type :peepoHappy:, this would be helpful as some emotes are real words, for example WHAT or Hmm. This would stop people from accidently typing emotes, which can be quite awkward if the convo is serious

**Comment by XspeedPL** [comment]
Valid request, but what about emotes that already have that prefix in them?
Like this one for example: https://7tv.app/emotes/01G9552ZJR0005FQ6YW3VH1Y20
`::o:`?

**Comment by Hinzy-Admin** [comment]
maybe another symbol? for example, ? # ~ or [] 
aka `[:o]`
Maybe it could be a config? so the users could choose?

**Comment by XspeedPL** [comment]
Configurable option sounds good, but to keep it simple I would limit it to a predefined list of choices:
- `:emote:`
- `(emote)`
- `[emote]`
- `emote`

In case of `:emote:`, `:o` would need to become `::o:`, while `:tf:` (global BTTV emote) would remain the same

**Comment by XspeedPL** [comment]
In the end, I thought additional options were unnecessary, unless someone requests it specifically, I will keep it to just `:`, configurable to be either disabled, optional or required
